FROM debian:stable-slim

ARG BIOME_VERSION=1.7.3

RUN apt-get update && apt-get install -y curl && \
    apt get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/bin
RUN curl -L "https://github.com/biomejs/biome/releases/download/cli%2Fv${BIOME_VERSION}/biome-linux-x64-musl" -o biome && \
    chmod +x biome

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/biome"]
